jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Run Tests
      run: ./gradlew testOssDebugUnitTest
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew assembleSnapshot
    - continue-on-error: true
      name: Upload Artifacts - OSS version
      uses: actions/upload-artifact@v2
      with:
        name: SkyTube-Oss.apk
        path: app/build/outputs/apk/oss/snapshot/SkyTube-Oss-*.apk
    - continue-on-error: true
      name: Upload Artifacts - Extra version
      uses: actions/upload-artifact@v2
      with:
        name: SkyTube-Extra.apk
        path: app/build/outputs/apk/extra/snapshot/SkyTube-Extra-*.apk
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
